package com.example.booking.exception;

public enum ExceptionDescription {

    PROVINCE_NOT_FOUND("PROVINCE_NOT_FOUND"),
    PROVINCE_ID_NOT_FOUND("PROVINCE_ID_NOT_FOUND"),
    PROVINCE_NAME_NOT_FOUND("PROVINCE_NAME_NOT_FOUND"),

    CUSTOMER_NOT_FOUND("CUSTOMER_NOT_FOUND"),
    CUSTOMER_FIRST_NAME_NOT_FOUND("CUSTOMER_FIRST_NAME_NOT_FOUND"),
    CUSTOMER_LAST_NAME_NOT_FOUND("CUSTOMER_LAST_NAME_NOT_FOUND"),
    CUSTOMER_ID_NOT_FOUND("CUSTOMER_ID_NOT_FOUND"),
    CUSTOMER_NOT_A_MEMBER("CUSTOMER_NOT_A_MEMBER"),

    DISTRICT_NOT_FOUND("DISTRICT_NOT_FOUND"),
    DISTRICT_NAME_NOT_FOUND("DISTRICT_NAME_NOT_FOUND"),
    DISTRICT_ID_NOT_FOUND("DISTRICT_ID_NOT_FOUND"),

    INSPECTION_STATION_ID_NOT_FOUND("INSPECTION_STATION_ID_NOT_FOUND"),
    INSPECTION_STATION_NAME_NOT_FOUND("INSPECTION_STATION_NAME_NOT_FOUND"),
    INSPECTION_STATION_NOT_FOUND("INSPECTION_STATION_NOT_FOUND"),
    VEHICLE_CAPACITY_NOT_FOUND("VEHICLE_CAPACITY_NOT_FOUND"),
    VEHICLE_CAPACITY_SHOULD_BE_10_OR_20("VEHICLE_CAPACITY_SHOULD_BE_10_OR_20"),

    REGISTER_ID_NOT_FOUND("REGISTER_ID_NOT_FOUND"),

    RESERVATION_ID_NOT_FOUND("RESERVATION_ID_NOT_FOUND"),
    RESERVATION_LICENSE_OWNER_NOT_FOUND("RESERVATION_LICENSE_OWNER_NOT_FOUND"),
    RESERVATION_DATE_TIME_NOT_FOUND("RESERVATION_DATE_TIME_NOT_FOUND"),
    RESERVATION_LICENSE_NUMBER_NOT_FOUND("RESERVATION_LICENSE_NUMBER_NOT_FOUND"),
    RESERVATION_HOUR_NOT_FOUND("RESERVATION_HOUR_NOT_FOUND"),
    RESERVATION_HOUR_IS_FULL("RESERVATION_HOUR_IS_FULL"),
    LICENSE_NUMBER_IS_USING("LICENSE_NUMBER_IS_USING"),

    THE_VEHICLE_INSPECTION_STATION_HAS_BEEN_RESERVED_SUCCESSFULLY("THE_VEHICLE_INSPECTION_STATION_HAS_BEEN_RESERVED_SUCCESSFULLY"),

    CHOOSE_FULL_OR_HALF_HOURS("CHOOSE_FULL_OR_HALF_HOURS"),
    CHOOSE_FULL_HOURS("CHOOSE_FULL_HOURS"),
    ;

    private String description;

    ExceptionDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

}
